apiVersion: v1
kind: Secret
metadata:
  name: fluent-bit-elasticsearch-password
  namespace: kapp
  annotations:
    kapp.k14s.io/change-group: "fluent-bit-overlays"
type: Opaque
stringData:
  elasticsearch-password.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@ load("@ytt:data", "data")
    #@overlay/match by=overlay.subset({"kind":"DaemonSet","metadata":{"name":"fluent-bit"}})
    ---
    spec:
      template:
        spec:
          containers:
          #@overlay/match by="name"
          - name: fluent-bit
            #@overlay/match missing_ok=True
            env:
            #@overlay/match by="name", missing_ok=True
            - name: ES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-es-elastic-user
                  key: elastic
    ---
    apiVersion: secretgen.carvel.dev/v1alpha1
    kind: SecretExport
    metadata:
      name: elasticsearch-es-elastic-user
      namespace: elastic-stack
    spec:
      toNamespace: "*"
    ---
    apiVersion: secretgen.carvel.dev/v1alpha1
    kind: SecretImport
    metadata:
      name: elasticsearch-es-elastic-user
      namespace: #@ data.values.namespace
    spec:
      fromNamespace: elastic-stack