apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package-ClusterRole: tap-tap-install-cluster-role
    tkg.tanzu.vmware.com/tanzu-package-ClusterRoleBinding: tap-tap-install-cluster-rolebinding
    tkg.tanzu.vmware.com/tanzu-package-Secret: tap-tap-install-values
    tkg.tanzu.vmware.com/tanzu-package-ServiceAccount: tap-tap-install-sa
    kapp.k14s.io/change-group: "{name}"
    kapp.k14s.io/change-rule.create-order.0: "upsert after upserting tap-install-rbac"
    kapp.k14s.io/change-rule.delete-order.0: "delete before deleting tap-install-rbac"
    kapp.k14s.io/change-rule.create-order.1: "upsert after upserting tap-install-values"
    kapp.k14s.io/change-rule.delete-order.1: "delete before deleting tap-install-values"
    kapp.k14s.io/change-rule.create-order.2: "upsert after upserting tap-install-overlays"
    kapp.k14s.io/change-rule.delete-order.2: "delete before deleting tap-install-overlays"
  name: tap
  namespace: tap-install
spec:
  packageRef:
    refName: tap.tanzu.vmware.com
    versionSelection:
      constraints: 1.1.1
  serviceAccountName: tap-tap-install-sa
  values:
  - secretRef:
      name: tap-tap-install-values