#@ load("@ytt:data", "data")
#@ for user in data.values.users:
#@ namespace = user.name.lower()
---
apiVersion: v1
kind: Namespace
metadata:
  name: #@ namespace
  labels:
    role: tap-developer
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: tap-registry
  namespace: #@ namespace
spec:
  fromNamespace: tap-install
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: registry-credentials
  namespace: #@ namespace
spec:
  fromNamespace: build-service
---
apiVersion: v1
kind: Secret
metadata:
  name: git-ssh
  namespace: #@ namespace
  annotations:
    tekton.dev/git-0: github.com
type: kubernetes.io/ssh-auth
stringData:
  ssh-privatekey: 🔑
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: #@ data.values.service_account
  namespace: #@ namespace
secrets:
- name: registry-credentials
- name: git-ssh
imagePullSecrets:
- name: registry-credentials
- name: tap-registry
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: #@ "{}-permit-deliverable".format(data.values.service_account)
  namespace: #@ namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: deliverable
subjects:
- kind: ServiceAccount
  name: #@ data.values.service_account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: #@ "{}-permit-workload".format(data.values.service_account)
  namespace: #@ namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: workload
subjects:
- kind: ServiceAccount
  name: #@ data.values.service_account
#@ for clusterrole in user.clusterroles:
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: #@ "{}-permit-{}".format(namespace, clusterrole)
  namespace: #@ namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: #@ clusterrole
subjects:
- kind: User
  name: #@ user.email
#@ end
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package-ClusterRole: #@ "grype-{}-tap-install-cluster-role".format(namespace)
    tkg.tanzu.vmware.com/tanzu-package-ClusterRoleBinding: #@ "grype-{}-tap-install-cluster-rolebinding".format(namespace)
    tkg.tanzu.vmware.com/tanzu-package-Secret: #@ "grype-{}-tap-install-values".format(namespace)
    tkg.tanzu.vmware.com/tanzu-package-ServiceAccount: #@ "grype-{}-tap-install-sa".format(namespace)
    kapp.k14s.io/change-rule.create-order.0: #@ "upsert after upserting grype-{}-tap-install-rbac".format(namespace)
    kapp.k14s.io/change-rule.delete-order.0: #@ "delete before deleting grype-{}-tap-install-rbac".format(namespace)
    kapp.k14s.io/change-rule.create-order.1: #@ "upsert after upserting grype-{}-tap-install-values".format(namespace)
    kapp.k14s.io/change-rule.delete-order.1: #@ "delete before deleting grype-{}-tap-install-values".format(namespace)
  name: #@ "grype-{}".format(namespace)
  namespace: tap-install
spec:
  packageRef:
    refName: grype.scanning.apps.tanzu.vmware.com
    versionSelection:
      constraints: 1.1.1
  serviceAccountName: #@ "grype-{}-tap-install-sa".format(namespace)
  values:
  - secretRef:
      name: #@ "grype-{}-tap-install-values".format(namespace)
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: #@ "grype-{}".format(namespace)
    kapp.k14s.io/change-group: #@ "grype-{}-tap-install-rbac".format(namespace)
  name: #@ "grype-{}-tap-install-cluster-role".format(namespace)
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: #@ "grype-{}".format(namespace)
    kapp.k14s.io/change-group: #@ "grype-{}-tap-install-rbac".format(namespace)
  name: #@ "grype-{}-tap-install-cluster-rolebinding".format(namespace)
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: #@ "grype-{}-tap-install-cluster-role".format(namespace)
subjects:
- kind: ServiceAccount
  name: #@ "grype-{}-tap-install-sa".format(namespace)
  namespace: tap-install
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: #@ "grype-{}".format(namespace)
    kapp.k14s.io/change-group: #@ "grype-{}-tap-install-rbac".format(namespace)
  name: #@ "grype-{}-tap-install-sa".format(namespace)
  namespace: tap-install
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: #@ "grype-{}".format(namespace)
    kapp.k14s.io/change-group: #@ "grype-{}-tap-install-values".format(namespace)
  name: #@ "grype-{}-tap-install-values".format(namespace)
  namespace: tap-install
type: Opaque
stringData:
  #@yaml/text-templated-strings
  values.yml: |
    namespace: (@= namespace @)
    targetImagePullSecret: registry-credentials
#@ end