apiVersion: v1
kind: ConfigMap
metadata:
  name: curator-config
  namespace: elastic-stack
data:
  config.yml: |
    client:
      hosts: elasticsearch-es-http.elastic-stack.svc.cluster.local
      port: 9200
      url_prefix:
      use_ssl: True
      certificate:
      client_cert:
      client_key:
      ssl_no_validate: True
      username: elastic
      password: ${ES_PASSWORD}
      timeout: 30
      master_only: False
    logging:
      loglevel: INFO
      logfile:
      logformat: default
      blacklist: [ 'elasticsearch', 'urllib3' ]
  actions.yml: |
    actions:
      1:
        action: delete_indices
        description: >-
          Delete indices older than 7 days (based on index name), for logstash-
          prefixed indices. Ignore the error if the filter does not result in an
          actionable list of indices (ignore_empty_list) and exit cleanly.
        options:
          ignore_empty_list: True
          disable_action: False
        filters:
        - filtertype: pattern
          kind: prefix
          value: logstash-
        - filtertype: age
          source: name
          direction: older
          timestring: '%Y.%m.%d'
          unit: days
          unit_count: 5
      2:
        action: delete_indices
        description: >-
          Delete indices older than 2 days (based on index name), for zipkin-span-
          prefixed indices. Ignore the error if the filter does not result in an
          actionable list of indices (ignore_empty_list) and exit cleanly.
        options:
          ignore_empty_list: True
          disable_action: False
        filters:
        - filtertype: pattern
          kind: prefix
          value: zipkin-span-
        - filtertype: age
          source: name
          direction: older
          timestring: '%Y-%m-%d'
          unit: days
          unit_count: 2
      3:
        action: delete_indices
        description: >-
          Delete indices older than 2 days (based on index name), for zipkin-dependency-
          prefixed indices. Ignore the error if the filter does not result in an
          actionable list of indices (ignore_empty_list) and exit cleanly.
        options:
          ignore_empty_list: True
          disable_action: False
        filters:
        - filtertype: pattern
          kind: prefix
          value: zipkin-dependency-
        - filtertype: age
          source: name
          direction: older
          timestring: '%Y-%m-%d'
          unit: days
          unit_count: 2
      4:
        action: delete_indices
        description: Delete .monitoring-es-7-yyyy.mm.dd
        options:
          ignore_empty_list: True
          disable_action: False
        filters:
        - filtertype: pattern
          kind: prefix
          value: .monitoring-es-7-
        - filtertype: age
          source: name
          direction: older
          timestring: '%Y.%m.%d'
          unit: days
          unit_count: 1
      5:
        action: delete_indices
        description: Delete .monitoring-kibana-7-yyyy.mm.dd
        options:
          ignore_empty_list: True
          disable_action: False
        filters:
        - filtertype: pattern
          kind: prefix
          value: .monitoring-kibana-7-
        - filtertype: age
          source: name
          direction: older
          timestring: '%Y.%m.%d'
          unit: days
          unit_count: 1
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: curator
  namespace: elastic-stack
spec:
  jobTemplate:
    metadata:
      name: curator
    spec:
      template:
        spec:
          containers:
          - name: curator
            image: docker.io/bitnami/elasticsearch-curator:5.8.4-debian-10-r353
            env:
            - name: ES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-es-elastic-user
                  key: elastic
            args:
            - --config
            - /etc/curator/config.yml
            - /etc/curator/actions.yml
            volumeMounts:
            - mountPath: /etc/curator/
              name: curator-config
              readOnly: true
          restartPolicy: OnFailure
          volumes:
          - configMap:
              name: curator-config
            name: curator-config
  schedule: 10 15 * * *
