#@ load("@ytt:data", "data")
apiVersion: v1
kind: Secret
metadata:
  name: tap-registry
  namespace: tap-install
type: kubernetes.io/dockerconfigjson
stringData:
  #@yaml/text-templated-strings
  .dockerconfigjson: |-
    {
      "auths": {
        "registry.pivotal.io": {
          "username": "(@= data.values.tanzunet.username @)",
          "password": "(@= data.values.tanzunet.password @)"
        },
        "registry.tanzu.vmware.com": {
          "username": "(@= data.values.tanzunet.username @)",
          "password": "(@= data.values.tanzunet.password @)"
        }
      }
    }
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: tap-registry
  namespace: tap-install
spec:
  toNamespaces:
  - '*'