apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package-ClusterRole: postgres-operator-tds-system-cluster-role
    tkg.tanzu.vmware.com/tanzu-package-ClusterRoleBinding: postgres-operator-tds-system-cluster-rolebinding
    tkg.tanzu.vmware.com/tanzu-package-Secret: postgres-operator-tds-system-values
    tkg.tanzu.vmware.com/tanzu-package-ServiceAccount: postgres-operator-tds-system-sa
    kapp.k14s.io/change-group: "{name}"
    kapp.k14s.io/change-rule.create-order.0: "upsert after upserting postgres-operator-rbac"
    kapp.k14s.io/change-rule.delete-order.0: "delete before deleting postgres-operator-rbac"
    kapp.k14s.io/change-rule.create-order.1: "upsert after upserting postgres-operator-values"
    kapp.k14s.io/change-rule.delete-order.1: "delete before deleting postgres-operator-values"
  name: postgres-operator
  namespace: tds-system
spec:
  packageRef:
    refName: postgres-operator.sql.tanzu.vmware.com
    versionSelection:
      constraints: 1.7.2+patch.1
      prereleases: { }
  serviceAccountName: postgres-operator-tds-system-sa
  values:
  - secretRef:
      name: postgres-operator-tds-system-values