apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package-ClusterRole: ootb-supply-chain-testing-tap-install-cluster-role
    tkg.tanzu.vmware.com/tanzu-package-ClusterRoleBinding: ootb-supply-chain-testing-tap-install-cluster-rolebinding
    tkg.tanzu.vmware.com/tanzu-package-Secret: ootb-supply-chain-testing-tap-install-values
    tkg.tanzu.vmware.com/tanzu-package-ServiceAccount: ootb-supply-chain-testing-tap-install-sa
    kapp.k14s.io/change-group: "{name}"
    kapp.k14s.io/change-rule.create-order.0: "upsert after upserting ootb-supply-chain-testing-install-rbac"
    kapp.k14s.io/change-rule.delete-order.0: "delete before deleting ootb-supply-chain-testing-install-rbac"
    kapp.k14s.io/change-rule.create-order.1: "upsert after upserting ootb-supply-chain-testing-install-values"
    kapp.k14s.io/change-rule.delete-order.1: "delete before deleting ootb-supply-chain-testing-install-values"
    kapp.k14s.io/change-rule.create-order.2: "upsert after upserting ootb-supply-chain-testing-install-overlays"
    kapp.k14s.io/change-rule.delete-order.2: "delete before deleting ootb-supply-chain-testing-install-overlays"
    ext.packaging.carvel.dev/ytt-paths-from-secret-name.0: ootb-supply-chain-testing-remove-image-to-url
  name: ootb-supply-chain-testing
  namespace: tap-install
spec:
  packageRef:
    refName: ootb-supply-chain-testing.tanzu.vmware.com
    versionSelection:
      constraints: 0.7.1
  serviceAccountName: ootb-supply-chain-testing-tap-install-sa
  values:
  - secretRef:
      name: ootb-supply-chain-testing-tap-install-values