apiVersion: v1
kind: Secret
metadata:
  name: full-tbs-deps-add-clusterbuilder
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: "full-tbs-deps-install-overlays"
type: Opaque
stringData:
  full-tbs-deps-add-clusterbuilder.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"metadata":{"name":"dependency-updater"}, "kind": "TanzuNetDependencyUpdater"})
    ---
    spec:
      inlineDescriptor:
        clusterStores:
        #@overlay/match by="name", missing_ok=True
        - name: default
          sources:
          #@overlay/append
          - image: ghcr.io/making/buildpacks/opentelemetry-javaagent:0.1.9
        clusterBuilders:
        #@overlay/append
        - name: java-otel
          clusterStack: base
          clusterStore: default
          order:
          - group:
            - id: tanzu-buildpacks/java
            - id: making/opentelemetry-javaagent
