apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: tbs-full-deps-repository
  namespace: tap-install
spec:
  fetch:
    imgpkgBundle:
      image: registry.tanzu.vmware.com/tanzu-application-platform/full-tbs-deps-package-repo:1.6.0