apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kapp.k14s.io/change-group: "{name}"
    kapp.k14s.io/change-rule.create-order: "upsert after upserting tsunagu-client-values"
    kapp.k14s.io/change-rule.delete-order: "delete before deleting tsunagu-client-values"
  name: tsunagu-client
  namespace: kapp
spec:
  packageRef:
    refName: tsunagu-client.tsunagu.ik.am
    versionSelection:
      constraints: 0.0.1
      prereleases: { }
  serviceAccountName: kapp
  values:
  - secretRef:
      name: tsunagu-client-values