apiVersion: v1
kind: Secret
metadata:
  name: cnrs-autocreate-cluster-domain-claims
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: "tap-install-overlays"
type: Opaque
stringData:
  cnrs-autocreate-cluster-domain-claims.yml: |
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"metadata":{"name":"config-network"}, "kind": "ConfigMap"})
    ---
    data:
      #@overlay/match missing_ok=True
      autocreate-cluster-domain-claims: "true"