apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package-ClusterRole: tanzu-rabbitmq-tds-system-cluster-role
    tkg.tanzu.vmware.com/tanzu-package-ClusterRoleBinding: tanzu-rabbitmq-tds-system-cluster-rolebinding
    tkg.tanzu.vmware.com/tanzu-package-Secret: tanzu-rabbitmq-tds-system-values
    tkg.tanzu.vmware.com/tanzu-package-ServiceAccount: tanzu-rabbitmq-tds-system-sa
    kapp.k14s.io/change-group: "{name}"
    kapp.k14s.io/change-rule.create-order.0: "upsert after upserting tanzu-rabbitmq-rbac"
    kapp.k14s.io/change-rule.delete-order.0: "delete before deleting tanzu-rabbitmq-rbac"
    kapp.k14s.io/change-rule.create-order.1: "upsert after upserting tanzu-rabbitmq-values"
    kapp.k14s.io/change-rule.delete-order.1: "delete before deleting tanzu-rabbitmq-values"
  name: tanzu-rabbitmq
  namespace: tds-system
spec:
  packageRef:
    refName: rabbitmq.tanzu.vmware.com
    versionSelection:
      constraints: 1.2.0
      prereleases: { }
  serviceAccountName: tanzu-rabbitmq-tds-system-sa
  values:
  - secretRef:
      name: tanzu-rabbitmq-tds-system-values